### ISSUE TITLE
Master wont build in Unity: Symbols not recognized

### ISSUE THREAD

**Issue by JarrettSJohnson** [happy30/DREditor#2]
![image](https://user-images.githubusercontent.com/36459667/63354591-b1c88380-c332-11e9-81a2-798c52dae4d1.png)

Discussed with the developer about this already.

**Comment by lordscales91** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Testing](https://trello.com/c/FKesYnhr/1-testing)
