### ISSUE TITLE
Non-interpersonal dialogue support

### ISSUE THREAD

**Issue by JarrettSJohnson** [happy30/DREditor#3]
One suggestion that I can easily work with is to have a 'no student/expression' option in dialogue lines. I can just read that information in and assume that this is meant for the protagonists' inner thoughts or for examining objects. This might be a quick fix for something that might need to be more robust though.

**Comment by happy30** [comment]
Good point that was overlooked. Protagonist support will be added to the editor.

**Comment by lordscales91** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Testing](https://trello.com/c/FKesYnhr/1-testing)

**Comment by JarrettSJohnson** [comment]
#10
