### ISSUE TITLE
Dialogue Editor: Add/Modify a line in/at an arbitrary position

### ISSUE THREAD

**Issue by JarrettSJohnson** [happy30/DREditor#5]
Seems like the editor only supports adding lines at the end. Would be extremely helpful to be able to add/move lines at/to different positions else it wouldn't be feasible to modify larger dialogue assets later on.

**Comment by lordscales91** [comment]
Actually, I think this sorting feature could be added to the [CharacterDatabaseEditor](https://github.com/happy30/DREditor/blob/2d6a90cbe7c1383f056c56bb745472d2af6a800d/Scripts/CharacterEditor/Editor/CharacterDatabaseEditor.cs) as well. It might be useful for organization purposes. Like, placing first the `Headmaster` and then the `Student`s (or the other way around).
