### ISSUE TITLE
Dialogue Editor doesn't cleans up expression when switching back to "No change"

### ISSUE THREAD

**Issue by lordscales91** [happy30/DREditor#8]
Like the title say, there's a bug where the `Expression` of the a line object is not cleaned up after selecting `<No change>` if it had a previous expression set. The root cause is on these lines: https://github.com/happy30/DREditor/blob/aa6ff4086138ae1a4130b834d64a325fa8b68f70/Scripts/DialogueEditor/Editor/DialogueEditor.cs#L303-L309

The expression is only changed when the value selected is greater than 0 (the `<No change>` option). Therefore, when the 0 is selected the Expression is not cleaned.

**Comment by JarrettSJohnson** [comment]
@lordscales91 can you check to see if that's still the case? Maybe I'm not fully understanding the problem, but I can't reproduce.

**Comment by lordscales91** [comment]
@JarrettSJohnson It's fixed on your fork, the key was the `else` here: 

https://github.com/JarrettSJohnson/DREditor/blob/33f418504fa33c4bdf43148135dbc8a126c520cf/Scripts/DialogueEditor/Editor/DialogueEditor.cs#L288-L296 

That else was not present in the referenced code.

So this one is also fixed by PR #10
